import { nanoid } from 'nanoid'
import type {
  AssumptionPack,
  ModelAssumption,
  UsageProfile,
  TaskPreset,
  UIPreferences,
} from '@/types/domain'

const now = new Date().toISOString()

// ---- System Assumption Pack --------------------------------

export const SYSTEM_ASSUMPTION_PACK: AssumptionPack = {
  id: 'system-pack-v1',
  name: 'Official Range Mode v1',
  version: '1.0.0',
  source: 'Microsoft Copilot Cowork documentation',
  sourceDate: '2025-01-01',
  description:
    'Assumption pack basato sulle bande pubblicate da Microsoft per light/medium/heavy task.',
  creditBands: {
    lightMin: 1,
    lightMid: 5,
    lightMax: 10,
    mediumMin: 11,
    mediumMid: 20,
    mediumMax: 40,
    heavyMin: 41,
    heavyMid: 75,
    heavyMax: 200,
  },
  modelFactors: {
    'model-auto': 1.0,
    'model-claude-sonnet': 1.2,
    'model-claude-opus': 2.0,
    'model-sonnet-opus-advisor': 1.6,
    'model-gpt5-frontier': 2.5,
    'model-imagen2': 1.8,
    'model-cowork1': 1.0,
  },
  factors: {
    contextLow: 1.0,
    contextMedium: 1.3,
    contextHigh: 1.8,
    toolsNone: 1.0,
    toolsLight: 1.2,
    toolsHeavy: 1.6,
    runtimeFast: 1.0,
    runtimeMedium: 1.3,
    runtimeSlow: 1.8,
    browserMultiplier: 1.4,
    imageMultiplier: 1.5,
  },
  fundingDefaults: {
    paygPricePerCredit: 0.01,
    currency: 'EUR',
  },
  isSystemDefault: true,
  disclaimer:
    'Queste sono stime basate su bande indicative. Non rappresentano un prezzo ufficiale o contrattuale Microsoft.',
  createdAt: now,
  updatedAt: now,
}

// ---- System Models ------------------------------------------

export const SYSTEM_MODELS: ModelAssumption[] = [
  {
    id: 'model-auto',
    name: 'Auto',
    provider: 'Microsoft',
    description: 'Selezione automatica del modello ottimale per il task.',
    modelClass: 'auto',
    modelFactor: 1.0,
    inputWeight: 1.0,
    outputWeight: 1.0,
    recommendedFor: ['general', 'all tasks'],
    availabilityNotes: 'Default per tutti i task.',
    isOfficiallyDocumented: true,
    isEditable: false,
    isEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'model-claude-sonnet',
    name: 'Claude Sonnet 4.6',
    provider: 'Anthropic',
    description: 'Modello bilanciato per task articolati con buona velocità.',
    modelClass: 'advanced',
    modelFactor: 1.2,
    inputWeight: 1.0,
    outputWeight: 1.1,
    recommendedFor: ['document analysis', 'report generation', 'summarization'],
    availabilityNotes: 'Disponibile in Copilot Cowork.',
    isOfficiallyDocumented: false,
    isEditable: true,
    isEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'model-claude-opus',
    name: 'Claude Opus 4.8',
    provider: 'Anthropic',
    description: 'Modello di alta capacità per task complessi e reasoning avanzato.',
    modelClass: 'frontier',
    modelFactor: 2.0,
    inputWeight: 1.0,
    outputWeight: 1.2,
    recommendedFor: ['deep research', 'legal review', 'complex analysis'],
    availabilityNotes: 'Consumo crediti elevato. Stima non ufficialmente documentata.',
    isOfficiallyDocumented: false,
    isEditable: true,
    isEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'model-sonnet-opus-advisor',
    name: 'Sonnet + Opus Advisor',
    provider: 'Anthropic',
    description: 'Combinazione di Sonnet per esecuzione e Opus per advisory.',
    modelClass: 'advanced',
    modelFactor: 1.6,
    inputWeight: 1.1,
    outputWeight: 1.1,
    recommendedFor: ['multi-step workflows', 'agent tasks'],
    availabilityNotes: 'Stima combinata. Non ufficialmente documentata.',
    isOfficiallyDocumented: false,
    isEditable: true,
    isEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'model-gpt5-frontier',
    name: 'GPT 5.5 Frontier',
    provider: 'OpenAI',
    description: 'Modello frontier OpenAI per task di massima complessità.',
    modelClass: 'frontier',
    modelFactor: 2.5,
    inputWeight: 1.2,
    outputWeight: 1.2,
    recommendedFor: ['deep research', 'code generation', 'complex reasoning'],
    availabilityNotes: 'Stima basata su model factor indicativo. Non ufficialmente documentata.',
    isOfficiallyDocumented: false,
    isEditable: true,
    isEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'model-imagen2',
    name: 'Imagen 2',
    provider: 'Google',
    description: 'Modello per generazione immagini.',
    modelClass: 'image',
    modelFactor: 1.8,
    inputWeight: 0.5,
    outputWeight: 1.5,
    recommendedFor: ['image generation', 'visual content'],
    availabilityNotes:
      'Disponibile solo per task image-related. Stima non ufficialmente documentata.',
    isOfficiallyDocumented: false,
    isEditable: true,
    isEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'model-cowork1',
    name: 'Cowork 1 (placeholder)',
    provider: 'Microsoft',
    description: 'Placeholder per futuro modello nativo Microsoft Cowork.',
    modelClass: 'standard',
    modelFactor: 1.0,
    inputWeight: 1.0,
    outputWeight: 1.0,
    recommendedFor: ['general'],
    availabilityNotes: 'Modello placeholder, factor da aggiornare quando disponibile.',
    isOfficiallyDocumented: false,
    isEditable: true,
    isEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
]

// ---- System Usage Profiles ----------------------------------

export const SYSTEM_USAGE_PROFILES: UsageProfile[] = [
  {
    id: 'profile-light',
    name: 'Light',
    description: 'Uso occasionale, task semplici, bassa frequenza.',
    usageLevel: 'light',
    lightTasksPerUserPerMonth: 30,
    mediumTasksPerUserPerMonth: 5,
    heavyTasksPerUserPerMonth: 1,
    defaultModelId: 'model-auto',
    contextFactor: 1.0,
    toolsFactor: 1.0,
    runtimeFactor: 1.0,
    browserFactor: 1.0,
    imageFactor: 1.0,
    recommendedFor: ['blue collar', 'field workers', 'operations'],
    examples: ['Bozze email brevi', 'Sintesi rapide', 'Classificazioni semplici'],
    notes: null,
    isSystemDefault: true,
    isEditable: false,
    source: 'system',
    assumptionPackId: null,
    metadata: {},
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'profile-medium',
    name: 'Medium',
    description: 'Uso ricorrente, task articolati, più richieste mensili.',
    usageLevel: 'medium',
    lightTasksPerUserPerMonth: 50,
    mediumTasksPerUserPerMonth: 20,
    heavyTasksPerUserPerMonth: 5,
    defaultModelId: 'model-auto',
    contextFactor: 1.3,
    toolsFactor: 1.2,
    runtimeFactor: 1.3,
    browserFactor: 1.0,
    imageFactor: 1.0,
    recommendedFor: ['white collar', 'sales', 'HR', 'finance'],
    examples: ['Report operativi', 'Analisi documenti', 'Supporto decisionale'],
    notes: null,
    isSystemDefault: true,
    isEditable: false,
    source: 'system',
    assumptionPackId: null,
    metadata: {},
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'profile-heavy',
    name: 'Heavy',
    description: 'Uso intensivo, task complessi, workflow avanzati.',
    usageLevel: 'heavy',
    lightTasksPerUserPerMonth: 60,
    mediumTasksPerUserPerMonth: 40,
    heavyTasksPerUserPerMonth: 20,
    defaultModelId: 'model-claude-sonnet',
    contextFactor: 1.8,
    toolsFactor: 1.6,
    runtimeFactor: 1.8,
    browserFactor: 1.4,
    imageFactor: 1.0,
    recommendedFor: ['executive', 'legal', 'IT', 'strategy', 'customer care avanzato'],
    examples: ['Deep research', 'Agent task', 'Legal document review', 'Analisi multi-step'],
    notes: null,
    isSystemDefault: true,
    isEditable: false,
    source: 'system',
    assumptionPackId: null,
    metadata: {},
    createdAt: now,
    updatedAt: now,
  },
]

// ---- System Task Presets ------------------------------------

export const SYSTEM_TASK_PRESETS: TaskPreset[] = [
  {
    id: 'task-simple-prompt',
    name: 'Simple Prompt',
    description: 'Prompt semplice senza tool o contesto esteso.',
    intensity: 'light',
    defaultCreditsMin: 1,
    defaultCreditsMid: 3,
    defaultCreditsMax: 8,
    recommendedModels: ['model-auto'],
    contextComplexity: 'low',
    toolsUsage: 'none',
    runtimeComplexity: 'fast',
    browserUsage: false,
    imageUsage: false,
    notes: null,
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'task-summarization',
    name: 'Document Summarization',
    description: 'Riassunto di un documento o testo esteso.',
    intensity: 'light',
    defaultCreditsMin: 2,
    defaultCreditsMid: 5,
    defaultCreditsMax: 10,
    recommendedModels: ['model-auto', 'model-claude-sonnet'],
    contextComplexity: 'medium',
    toolsUsage: 'none',
    runtimeComplexity: 'fast',
    browserUsage: false,
    imageUsage: false,
    notes: null,
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'task-document-analysis',
    name: 'Document Analysis',
    description: 'Analisi approfondita di documenti con estrazione insight.',
    intensity: 'medium',
    defaultCreditsMin: 10,
    defaultCreditsMid: 20,
    defaultCreditsMax: 40,
    recommendedModels: ['model-claude-sonnet', 'model-claude-opus'],
    contextComplexity: 'high',
    toolsUsage: 'light',
    runtimeComplexity: 'medium',
    browserUsage: false,
    imageUsage: false,
    notes: null,
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'task-deep-research',
    name: 'Deep Research',
    description: 'Ricerca approfondita su argomenti complessi, multi-step.',
    intensity: 'heavy',
    defaultCreditsMin: 41,
    defaultCreditsMid: 80,
    defaultCreditsMax: 150,
    recommendedModels: ['model-claude-opus', 'model-gpt5-frontier'],
    contextComplexity: 'high',
    toolsUsage: 'heavy',
    runtimeComplexity: 'slow',
    browserUsage: true,
    imageUsage: false,
    notes: 'Consumo molto elevato per ricerche multi-source con browser.',
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'task-agent-task',
    name: 'Agent Task',
    description: 'Task eseguito da un agente autonomo con tool multipli.',
    intensity: 'heavy',
    defaultCreditsMin: 50,
    defaultCreditsMid: 100,
    defaultCreditsMax: 200,
    recommendedModels: ['model-sonnet-opus-advisor', 'model-claude-opus'],
    contextComplexity: 'high',
    toolsUsage: 'heavy',
    runtimeComplexity: 'slow',
    browserUsage: false,
    imageUsage: false,
    notes: 'Task agente con invocazione ripetuta di tool e gestione stato.',
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'task-multi-step-workflow',
    name: 'Multi-step Workflow',
    description: 'Workflow con più passaggi, dati multipli e decisioni intermedie.',
    intensity: 'heavy',
    defaultCreditsMin: 45,
    defaultCreditsMid: 90,
    defaultCreditsMax: 180,
    recommendedModels: ['model-sonnet-opus-advisor'],
    contextComplexity: 'high',
    toolsUsage: 'heavy',
    runtimeComplexity: 'slow',
    browserUsage: false,
    imageUsage: false,
    notes: null,
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'task-customer-support',
    name: 'Customer Support Automation',
    description: 'Gestione automatizzata di richieste cliente via AI.',
    intensity: 'medium',
    defaultCreditsMin: 8,
    defaultCreditsMid: 18,
    defaultCreditsMax: 35,
    recommendedModels: ['model-auto', 'model-claude-sonnet'],
    contextComplexity: 'medium',
    toolsUsage: 'light',
    runtimeComplexity: 'medium',
    browserUsage: false,
    imageUsage: false,
    notes: null,
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'task-sales-research',
    name: 'Sales Research',
    description: 'Ricerca su prospect, competitor e opportunità di mercato.',
    intensity: 'medium',
    defaultCreditsMin: 12,
    defaultCreditsMid: 25,
    defaultCreditsMax: 45,
    recommendedModels: ['model-claude-sonnet', 'model-gpt5-frontier'],
    contextComplexity: 'high',
    toolsUsage: 'light',
    runtimeComplexity: 'medium',
    browserUsage: true,
    imageUsage: false,
    notes: 'Uso browser aumenta il consumo stimato.',
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'task-legal-review',
    name: 'Legal Document Review',
    description: 'Revisione e analisi di documenti legali complessi.',
    intensity: 'heavy',
    defaultCreditsMin: 40,
    defaultCreditsMid: 75,
    defaultCreditsMax: 160,
    recommendedModels: ['model-claude-opus', 'model-gpt5-frontier'],
    contextComplexity: 'high',
    toolsUsage: 'light',
    runtimeComplexity: 'slow',
    browserUsage: false,
    imageUsage: false,
    notes: 'Contesto esteso per documenti lunghi.',
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'task-report-generation',
    name: 'Report Generation',
    description: 'Generazione automatica di report strutturati.',
    intensity: 'medium',
    defaultCreditsMin: 15,
    defaultCreditsMid: 30,
    defaultCreditsMax: 55,
    recommendedModels: ['model-claude-sonnet'],
    contextComplexity: 'medium',
    toolsUsage: 'light',
    runtimeComplexity: 'medium',
    browserUsage: false,
    imageUsage: false,
    notes: null,
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'task-data-extraction',
    name: 'Data Extraction',
    description: 'Estrazione dati strutturati da documenti non strutturati.',
    intensity: 'medium',
    defaultCreditsMin: 10,
    defaultCreditsMid: 22,
    defaultCreditsMax: 42,
    recommendedModels: ['model-auto', 'model-claude-sonnet'],
    contextComplexity: 'medium',
    toolsUsage: 'light',
    runtimeComplexity: 'medium',
    browserUsage: false,
    imageUsage: false,
    notes: null,
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'task-browser-research',
    name: 'Browser-based Research',
    description: 'Ricerca con navigazione web e raccolta dati da fonti online.',
    intensity: 'heavy',
    defaultCreditsMin: 50,
    defaultCreditsMid: 95,
    defaultCreditsMax: 190,
    recommendedModels: ['model-gpt5-frontier', 'model-claude-opus'],
    contextComplexity: 'high',
    toolsUsage: 'heavy',
    runtimeComplexity: 'slow',
    browserUsage: true,
    imageUsage: false,
    notes: 'Uso browser e tool aumentano significativamente il consumo.',
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'task-image-generation',
    name: 'Image Generation',
    description: 'Generazione di immagini tramite modello AI dedicato.',
    intensity: 'heavy',
    defaultCreditsMin: 40,
    defaultCreditsMid: 70,
    defaultCreditsMax: 120,
    recommendedModels: ['model-imagen2'],
    contextComplexity: 'low',
    toolsUsage: 'none',
    runtimeComplexity: 'medium',
    browserUsage: false,
    imageUsage: true,
    notes: 'Richiede modello image-specific. Consumo per immagine generata.',
    isSystemDefault: true,
    createdAt: now,
    updatedAt: now,
  },
]

// ---- Default UI Preferences --------------------------------

export const DEFAULT_PREFERENCES: UIPreferences = {
  theme: 'system',
  language: 'it',
  displayMode: 'range',
  defaultValueDisplay: 'mid',
  currency: 'EUR',
}

// ---- Segment templates for quick setup ----------------------

export interface SegmentTemplate {
  id: string
  name: string
  nameEn: string
  usageProfileId: string
  defaultEnabledPct: number
  defaultActivePct: number
}

export const SEGMENT_TEMPLATES: SegmentTemplate[] = [
  { id: nanoid(), name: 'Manager', nameEn: 'Managers', usageProfileId: 'profile-medium', defaultEnabledPct: 80, defaultActivePct: 70 },
  { id: nanoid(), name: 'Dirigenti', nameEn: 'Executives', usageProfileId: 'profile-heavy', defaultEnabledPct: 100, defaultActivePct: 80 },
  { id: nanoid(), name: 'White Collar', nameEn: 'White Collar', usageProfileId: 'profile-medium', defaultEnabledPct: 60, defaultActivePct: 50 },
  { id: nanoid(), name: 'Blue Collar', nameEn: 'Blue Collar', usageProfileId: 'profile-light', defaultEnabledPct: 20, defaultActivePct: 15 },
  { id: nanoid(), name: 'Sales', nameEn: 'Sales', usageProfileId: 'profile-heavy', defaultEnabledPct: 80, defaultActivePct: 65 },
  { id: nanoid(), name: 'HR', nameEn: 'HR', usageProfileId: 'profile-medium', defaultEnabledPct: 70, defaultActivePct: 55 },
  { id: nanoid(), name: 'Legal', nameEn: 'Legal', usageProfileId: 'profile-heavy', defaultEnabledPct: 90, defaultActivePct: 75 },
  { id: nanoid(), name: 'Finance', nameEn: 'Finance', usageProfileId: 'profile-medium', defaultEnabledPct: 75, defaultActivePct: 60 },
  { id: nanoid(), name: 'IT', nameEn: 'IT', usageProfileId: 'profile-heavy', defaultEnabledPct: 100, defaultActivePct: 85 },
  { id: nanoid(), name: 'Customer Care', nameEn: 'Customer Care', usageProfileId: 'profile-medium', defaultEnabledPct: 70, defaultActivePct: 60 },
  { id: nanoid(), name: 'Field Workers', nameEn: 'Field Workers', usageProfileId: 'profile-light', defaultEnabledPct: 25, defaultActivePct: 20 },
  { id: nanoid(), name: 'Operations', nameEn: 'Operations', usageProfileId: 'profile-light', defaultEnabledPct: 40, defaultActivePct: 30 },
]
